product = FactoryBot.create(:product, sku: '2i3enjn')
Admin.create(email:'admin@mercadores.com.br', password: '123456')
user = User.create(email: 'user1@gmail.com', password: '123456')
user2 = User.create(email: 'user2@gmail.com', password: '123456')
Cart.create(user: user, shipping_id: '1', product: product)
Evaluation.create(user: user, rate: 4, product: product, comment: 'algum comentario')
Evaluation.create(user: user2, rate: 3, product: product, comment: 'algum comentario')
product.update(average_rating: 3.5)